name: "Cache flutter"
description: "Cache artifacts like dependencies and build outputs to improve workflow execution time"
inputs:
  pubspec:
    description: 'cache pubspec'
    required: false
    default: 'true'
  pubspec-lock-file:
    description: 'cache pubspec'
    required: false
    default: '**/pubspec.lock'    
  pub-cache:
    description: ''
    required: false
    default: '/root/.pub-cache'
  cache_build_runner:
    description: 'cache build_runner output'
    required: false
    default: 'true'
  cache_build_runner_path:
    description: 'cache build_runner output'
    required: false
    default: |
      **/.dart_tool
      **/*.g.dart
      **/*.mocks.dart
      **/*.config.dart
      **/*.freezed.dart
      **/injector.config.dart
      **.gr.dart      
runs:
  using: "composite"
  steps:
    - name: Check PUB_CACHE presence
      id: check-pub-cache-env
      shell: bash
      run: |
        if [ "$PUB_CACHE" == "" ]; then
          echo ::set-output name=PUB_CACHE::${{ inputs.pub-cache }}
        else
          echo ::set-output name=PUB_CACHE::${{ env.PUB_CACHE }}
        fi
    - name: Cache pubspec dependencies
      id: cache-pubspec
      uses: actions/cache@v3
      if: inputs.pubspec == 'true'
      with:
        path: |
          ${{ steps.check-pub-cache-env.outputs.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles( inputs.pubspec-lock-file ) }}
        restore-keys: |
          build-pubspec-
    - name: Cache build runner
      id: cache-build_runner
      uses: actions/cache@v3
      if: inputs.cache_build_runner == 'true'
      with:
        path: {{ inputs.cache_build_runner_path }}
        key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', inputs.pubspec-lock-file , '**/outputs.json') }}
        restore-keys: |
            build-runner-
